/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package prog24178.project;

/**
 *
 * @author mikkelharris
 */
public class FACEBoneDetails extends javax.swing.JFrame
{

    /**
     * Creates new form FACEBoneDetails
     */
    public FACEBoneDetails(String caseNum)
    {
	initComponents();
    }
    public FACEBoneDetails()
    {
	
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jPanel10 = new javax.swing.JPanel();
        pnlLabel = new javax.swing.JPanel();
        lblCaseNum = new javax.swing.JLabel();
        pnlNF = new javax.swing.JPanel();
        pnlNFRegion = new javax.swing.JPanel();
        ddlNFRegion = new javax.swing.JComboBox();
        scrNFRegion = new javax.swing.JScrollPane();
        lstNFRegion = new javax.swing.JList();
        jLabel2 = new javax.swing.JLabel();
        pnlNFButtons = new javax.swing.JPanel();
        btnNFUpdate = new javax.swing.JButton();
        pnlNFDetails = new javax.swing.JPanel();
        scrNFDetails = new javax.swing.JScrollPane();
        txtNFDetails = new javax.swing.JTextArea();
        chkNFFound = new javax.swing.JCheckBox();
        pnlFound = new javax.swing.JPanel();
        pnlFButtons = new javax.swing.JPanel();
        pnlFUpdate = new javax.swing.JButton();
        pnlFBack = new javax.swing.JButton();
        pnlFRegion = new javax.swing.JPanel();
        ddlFRegion = new javax.swing.JComboBox();
        scrFRegion = new javax.swing.JScrollPane();
        lstFRegion = new javax.swing.JList();
        jLabel3 = new javax.swing.JLabel();
        pnlFDetails = new javax.swing.JPanel();
        scrFDetails = new javax.swing.JScrollPane();
        txtFDetails = new javax.swing.JTextArea();
        chkFFound = new javax.swing.JCheckBox();

        org.jdesktop.layout.GroupLayout jPanel2Layout = new org.jdesktop.layout.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 100, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 100, Short.MAX_VALUE)
        );

        jLabel1.setText("jLabel1");

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        org.jdesktop.layout.GroupLayout jPanel10Layout = new org.jdesktop.layout.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 100, Short.MAX_VALUE)
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pnlLabel.setLayout(new java.awt.BorderLayout());

        lblCaseNum.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCaseNum.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Case Number", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION));
        pnlLabel.add(lblCaseNum, java.awt.BorderLayout.CENTER);

        pnlNF.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Not Found", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION));
        pnlNF.setLayout(new java.awt.BorderLayout());

        ddlNFRegion.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        scrNFRegion.setViewportView(lstNFRegion);

        jLabel2.setText("Body Region");

        org.jdesktop.layout.GroupLayout pnlNFRegionLayout = new org.jdesktop.layout.GroupLayout(pnlNFRegion);
        pnlNFRegion.setLayout(pnlNFRegionLayout);
        pnlNFRegionLayout.setHorizontalGroup(
            pnlNFRegionLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(pnlNFRegionLayout.createSequentialGroup()
                .add(pnlNFRegionLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(pnlNFRegionLayout.createSequentialGroup()
                        .add(6, 6, 6)
                        .add(scrNFRegion, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                    .add(pnlNFRegionLayout.createSequentialGroup()
                        .addContainerGap()
                        .add(jLabel2)
                        .add(0, 0, Short.MAX_VALUE))
                    .add(ddlNFRegion, 0, 114, Short.MAX_VALUE))
                .addContainerGap())
        );
        pnlNFRegionLayout.setVerticalGroup(
            pnlNFRegionLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(pnlNFRegionLayout.createSequentialGroup()
                .addContainerGap()
                .add(jLabel2)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(ddlNFRegion, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 24, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(scrNFRegion, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 214, Short.MAX_VALUE))
        );

        pnlNF.add(pnlNFRegion, java.awt.BorderLayout.LINE_START);

        btnNFUpdate.setText("Update");

        org.jdesktop.layout.GroupLayout pnlNFButtonsLayout = new org.jdesktop.layout.GroupLayout(pnlNFButtons);
        pnlNFButtons.setLayout(pnlNFButtonsLayout);
        pnlNFButtonsLayout.setHorizontalGroup(
            pnlNFButtonsLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(pnlNFButtonsLayout.createSequentialGroup()
                .add(131, 131, 131)
                .add(btnNFUpdate)
                .addContainerGap(157, Short.MAX_VALUE))
        );
        pnlNFButtonsLayout.setVerticalGroup(
            pnlNFButtonsLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, pnlNFButtonsLayout.createSequentialGroup()
                .add(0, 0, Short.MAX_VALUE)
                .add(btnNFUpdate))
        );

        pnlNF.add(pnlNFButtons, java.awt.BorderLayout.PAGE_END);

        scrNFDetails.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        txtNFDetails.setColumns(20);
        txtNFDetails.setRows(5);
        txtNFDetails.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Bone Details", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION));
        scrNFDetails.setViewportView(txtNFDetails);

        chkNFFound.setText("Bone Found");

        org.jdesktop.layout.GroupLayout pnlNFDetailsLayout = new org.jdesktop.layout.GroupLayout(pnlNFDetails);
        pnlNFDetails.setLayout(pnlNFDetailsLayout);
        pnlNFDetailsLayout.setHorizontalGroup(
            pnlNFDetailsLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(pnlNFDetailsLayout.createSequentialGroup()
                .addContainerGap()
                .add(chkNFFound)
                .addContainerGap())
            .add(scrNFDetails)
        );
        pnlNFDetailsLayout.setVerticalGroup(
            pnlNFDetailsLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, pnlNFDetailsLayout.createSequentialGroup()
                .add(20, 20, 20)
                .add(chkNFFound)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(scrNFDetails, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 217, Short.MAX_VALUE))
        );

        pnlNF.add(pnlNFDetails, java.awt.BorderLayout.CENTER);

        pnlFound.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Found", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION));
        pnlFound.setLayout(new java.awt.BorderLayout());

        pnlFUpdate.setText("Update");

        pnlFBack.setText("Back");

        org.jdesktop.layout.GroupLayout pnlFButtonsLayout = new org.jdesktop.layout.GroupLayout(pnlFButtons);
        pnlFButtons.setLayout(pnlFButtonsLayout);
        pnlFButtonsLayout.setHorizontalGroup(
            pnlFButtonsLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(pnlFButtonsLayout.createSequentialGroup()
                .add(131, 131, 131)
                .add(pnlFUpdate)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 74, Short.MAX_VALUE)
                .add(pnlFBack, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 88, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        pnlFButtonsLayout.setVerticalGroup(
            pnlFButtonsLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, pnlFButtonsLayout.createSequentialGroup()
                .add(0, 0, Short.MAX_VALUE)
                .add(pnlFButtonsLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(pnlFUpdate)
                    .add(pnlFBack)))
        );

        pnlFound.add(pnlFButtons, java.awt.BorderLayout.PAGE_END);

        ddlFRegion.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        scrFRegion.setViewportView(lstFRegion);

        jLabel3.setText("Body Region");

        org.jdesktop.layout.GroupLayout pnlFRegionLayout = new org.jdesktop.layout.GroupLayout(pnlFRegion);
        pnlFRegion.setLayout(pnlFRegionLayout);
        pnlFRegionLayout.setHorizontalGroup(
            pnlFRegionLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(pnlFRegionLayout.createSequentialGroup()
                .addContainerGap()
                .add(jLabel3)
                .addContainerGap())
            .add(ddlFRegion, 0, 117, Short.MAX_VALUE)
            .add(pnlFRegionLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                .add(pnlFRegionLayout.createSequentialGroup()
                    .addContainerGap()
                    .add(scrFRegion, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 105, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        pnlFRegionLayout.setVerticalGroup(
            pnlFRegionLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(pnlFRegionLayout.createSequentialGroup()
                .addContainerGap()
                .add(jLabel3)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(ddlFRegion, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 28, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(216, Short.MAX_VALUE))
            .add(pnlFRegionLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                .add(org.jdesktop.layout.GroupLayout.TRAILING, pnlFRegionLayout.createSequentialGroup()
                    .add(0, 58, Short.MAX_VALUE)
                    .add(scrFRegion, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 214, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
        );

        pnlFound.add(pnlFRegion, java.awt.BorderLayout.LINE_START);

        scrFDetails.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        txtFDetails.setColumns(20);
        txtFDetails.setRows(5);
        txtFDetails.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Bone Details", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION));
        scrFDetails.setViewportView(txtFDetails);

        chkFFound.setText("Bone Found");

        org.jdesktop.layout.GroupLayout pnlFDetailsLayout = new org.jdesktop.layout.GroupLayout(pnlFDetails);
        pnlFDetails.setLayout(pnlFDetailsLayout);
        pnlFDetailsLayout.setHorizontalGroup(
            pnlFDetailsLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(pnlFDetailsLayout.createSequentialGroup()
                .add(pnlFDetailsLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, pnlFDetailsLayout.createSequentialGroup()
                        .add(4, 4, 4)
                        .add(scrFDetails, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 260, Short.MAX_VALUE))
                    .add(pnlFDetailsLayout.createSequentialGroup()
                        .addContainerGap()
                        .add(chkFFound)
                        .add(0, 153, Short.MAX_VALUE)))
                .addContainerGap())
        );
        pnlFDetailsLayout.setVerticalGroup(
            pnlFDetailsLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, pnlFDetailsLayout.createSequentialGroup()
                .add(22, 22, 22)
                .add(chkFFound)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(scrFDetails, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 215, Short.MAX_VALUE))
        );

        pnlFound.add(pnlFDetails, java.awt.BorderLayout.CENTER);

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(pnlLabel, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .add(layout.createSequentialGroup()
                .add(pnlNF, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 388, Short.MAX_VALUE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(pnlFound, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 399, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(pnlLabel, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 39, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(pnlNF, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .add(pnlFound, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
	/*
	 * Set the Nimbus look and feel
	 */
	//<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
	 * If Nimbus (introduced in Java SE 6) is not available, stay with the
	 * default look and feel. For details see
	 * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
	 */
	try
	{
	    for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
	    {
		if ("Nimbus".equals(info.getName()))
		{
		    javax.swing.UIManager.setLookAndFeel(info.getClassName());
		    break;
		}
	    }
	} catch (ClassNotFoundException ex)
	{
	    java.util.logging.Logger.getLogger(FACEBoneDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
	} catch (InstantiationException ex)
	{
	    java.util.logging.Logger.getLogger(FACEBoneDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
	} catch (IllegalAccessException ex)
	{
	    java.util.logging.Logger.getLogger(FACEBoneDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
	} catch (javax.swing.UnsupportedLookAndFeelException ex)
	{
	    java.util.logging.Logger.getLogger(FACEBoneDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
	}
	//</editor-fold>

	/*
	 * Create and display the form
	 */
	java.awt.EventQueue.invokeLater(new Runnable()
	{

	    public void run()
	    {
		new FACEBoneDetails().setVisible(true);
	    }
	});
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnNFUpdate;
    private javax.swing.JCheckBox chkFFound;
    private javax.swing.JCheckBox chkNFFound;
    private javax.swing.JComboBox ddlFRegion;
    private javax.swing.JComboBox ddlNFRegion;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JLabel lblCaseNum;
    private javax.swing.JList lstFRegion;
    private javax.swing.JList lstNFRegion;
    private javax.swing.JButton pnlFBack;
    private javax.swing.JPanel pnlFButtons;
    private javax.swing.JPanel pnlFDetails;
    private javax.swing.JPanel pnlFRegion;
    private javax.swing.JButton pnlFUpdate;
    private javax.swing.JPanel pnlFound;
    private javax.swing.JPanel pnlLabel;
    private javax.swing.JPanel pnlNF;
    private javax.swing.JPanel pnlNFButtons;
    private javax.swing.JPanel pnlNFDetails;
    private javax.swing.JPanel pnlNFRegion;
    private javax.swing.JScrollPane scrFDetails;
    private javax.swing.JScrollPane scrFRegion;
    private javax.swing.JScrollPane scrNFDetails;
    private javax.swing.JScrollPane scrNFRegion;
    private javax.swing.JTextArea txtFDetails;
    private javax.swing.JTextArea txtNFDetails;
    // End of variables declaration//GEN-END:variables
}
