 /*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package prog24178.project;

import java.awt.Window;
import java.awt.event.*;
import java.io.*;
import java.util.*;
import javax.swing.JOptionPane;

/**
 *
 * @author mikkelharris
 */
public class FACECaseSummary extends javax.swing.JFrame implements ActionListener, WindowListener
{
    // private PrintWriter caseLog;
    private PrintWriter boneTemp;
    
    ArrayList boneArray = new ArrayList(210);
    /**
     * Creates new form FACE1
     */
    
    public FACECaseSummary(String caseNum)
    {
	initComponents();
	btnEdit.addActionListener(this);
	btnExitCase.addActionListener(this);
	
	lblCaseNumber.setText(caseNum);
	txtRemainsList.setText(String.format("%-20s %-25s\n\n", "Bone","Details"));
	
	try
	{
	    boneTemp = new PrintWriter(new BufferedWriter(new FileWriter("bonesTemp.dat", true)));

	} catch (IOException ex)
	{
	    // display an error dialog
	    JOptionPane.showMessageDialog(null,
		    "Error accessing data file:\n"
		    + ex.toString(), "Error",
		    JOptionPane.ERROR_MESSAGE);
	}
	
	createArray("bones.dat", caseNum);
	for (int i = 0; i < boneArray.size(); i++)
	{
	    BoneInfo bone = (BoneInfo)boneArray.get(i);
	    txtRemainsList.append(String.format("%-20s %-25s",bone.getBoneName(), bone.getCondition()));
	    txtRemainsList.append("\n");
	    
	}
	txtRemainsList.setEditable(false);
	
    }
    public FACECaseSummary()
    {
	initComponents();
	btnEdit.addActionListener(this);
	btnExitCase.addActionListener(this);
	this.addWindowListener(this);
    }

    @Override
    public void actionPerformed(ActionEvent event)
    {
	Object source = event.getSource();
	FACEBoneDetails faceBoneDetails = new FACEBoneDetails(lblCaseNumber.getText());
	faceBoneDetails.pack();
	FACEStart faceStart = new FACEStart();
	faceStart.pack();
	
	if (source == btnEdit)
	{
	    faceBoneDetails.setVisible(true);
	    faceBoneDetails.pack();
	    //this.setVisible(false);
	    this.dispose();
	}
	else if (source == btnExitCase)
	{
	    faceStart.setVisible(true);
	    this.setVisible(false);
	}
    }
    
    private String readArray(String casefile)
    {
	return "";
    }
    
    private void createArray(String casefile, String caseNum)
    {
	try
	{
	    Scanner fileIn = new Scanner(new File(casefile));
	    fileIn.useDelimiter(System.getProperty("line.separator"));
	    
	    while (fileIn.hasNext())
	    {
		String record = fileIn.next();
		String[] fields = record.split("\\s*\\|\\s*");
		BoneInfo bone = new BoneInfo(fields[0], fields[1], fields[2], 
			fields[3], Boolean.parseBoolean(fields[4]));
		if (fields[0].trim().equals(caseNum))
		{
		    boneArray.add(bone); 
		    boneTemp.print(bone.toFileString()); 
		}
	    }
	}
	catch (IOException ex){}
	boneTemp.close();
    }
    @Override
    public void windowDeactivated(WindowEvent event){}
    @Override
    public void windowActivated(WindowEvent event){}
    @Override
    public void windowDeiconified(WindowEvent event){}
    @Override
    public void windowIconified(WindowEvent event){}
    @Override
    public void windowClosed(WindowEvent event){}
    @Override
    public void windowClosing(WindowEvent event){}
    @Override
    public void windowOpened(WindowEvent event){}
    /**
     * This method is called from within the constructor to initialize the form.
     * : Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollBar1 = new javax.swing.JScrollBar();
        pnlDisplay = new javax.swing.JPanel();
        scrRemainsList = new javax.swing.JScrollPane();
        txtRemainsList = new javax.swing.JTextArea();
        pnlCaseNumber = new javax.swing.JPanel();
        lblCaseNumber = new javax.swing.JLabel();
        pnlButtons = new javax.swing.JPanel();
        btnExitCase = new javax.swing.JButton();
        btnEdit = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Forensic Anthropology Case Evidence  (FACE) ");
        setSize(new java.awt.Dimension(600, 450));

        scrRemainsList.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        txtRemainsList.setColumns(20);
        txtRemainsList.setFont(new java.awt.Font("Courier New", 0, 13)); // NOI18N
        txtRemainsList.setRows(5);
        txtRemainsList.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Remains Recovered", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION));
        scrRemainsList.setViewportView(txtRemainsList);

        org.jdesktop.layout.GroupLayout pnlDisplayLayout = new org.jdesktop.layout.GroupLayout(pnlDisplay);
        pnlDisplay.setLayout(pnlDisplayLayout);
        pnlDisplayLayout.setHorizontalGroup(
            pnlDisplayLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(pnlDisplayLayout.createSequentialGroup()
                .addContainerGap()
                .add(scrRemainsList, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 359, Short.MAX_VALUE)
                .addContainerGap())
        );
        pnlDisplayLayout.setVerticalGroup(
            pnlDisplayLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(pnlDisplayLayout.createSequentialGroup()
                .add(scrRemainsList, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 210, Short.MAX_VALUE)
                .add(8, 8, 8))
        );

        getContentPane().add(pnlDisplay, java.awt.BorderLayout.CENTER);

        lblCaseNumber.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCaseNumber.setText(" ");
        lblCaseNumber.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Case Number", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION));

        org.jdesktop.layout.GroupLayout pnlCaseNumberLayout = new org.jdesktop.layout.GroupLayout(pnlCaseNumber);
        pnlCaseNumber.setLayout(pnlCaseNumberLayout);
        pnlCaseNumberLayout.setHorizontalGroup(
            pnlCaseNumberLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, lblCaseNumber, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 371, Short.MAX_VALUE)
        );
        pnlCaseNumberLayout.setVerticalGroup(
            pnlCaseNumberLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, pnlCaseNumberLayout.createSequentialGroup()
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .add(lblCaseNumber)
                .addContainerGap())
        );

        getContentPane().add(pnlCaseNumber, java.awt.BorderLayout.PAGE_START);

        btnExitCase.setText("Exit Case");

        btnEdit.setText("Edit");

        org.jdesktop.layout.GroupLayout pnlButtonsLayout = new org.jdesktop.layout.GroupLayout(pnlButtons);
        pnlButtons.setLayout(pnlButtonsLayout);
        pnlButtonsLayout.setHorizontalGroup(
            pnlButtonsLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(pnlButtonsLayout.createSequentialGroup()
                .add(67, 67, 67)
                .add(btnEdit, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 111, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(18, 18, 18)
                .add(btnExitCase)
                .addContainerGap(64, Short.MAX_VALUE))
        );

        pnlButtonsLayout.linkSize(new java.awt.Component[] {btnEdit, btnExitCase}, org.jdesktop.layout.GroupLayout.HORIZONTAL);

        pnlButtonsLayout.setVerticalGroup(
            pnlButtonsLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, pnlButtonsLayout.createSequentialGroup()
                .add(pnlButtonsLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(btnEdit)
                    .add(btnExitCase, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 23, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(pnlButtons, java.awt.BorderLayout.PAGE_END);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
	/*
	 * Set the Nimbus look and feel
	 */
	//<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
	 * If Nimbus (introduced in Java SE 6) is not available, stay with the
	 * default look and feel. For details see
	 * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
	 */
	try
	{
	    for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
	    {
		if ("Nimbus".equals(info.getName()))
		{
		    javax.swing.UIManager.setLookAndFeel(info.getClassName());
		    break;
		}
	    }
	} catch (ClassNotFoundException ex)
	{
	    java.util.logging.Logger.getLogger(FACECaseSummary.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
	} catch (InstantiationException ex)
	{
	    java.util.logging.Logger.getLogger(FACECaseSummary.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
	} catch (IllegalAccessException ex)
	{
	    java.util.logging.Logger.getLogger(FACECaseSummary.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
	} catch (javax.swing.UnsupportedLookAndFeelException ex)
	{
	    java.util.logging.Logger.getLogger(FACECaseSummary.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
	}
	//</editor-fold>

	/*
	 * Create and display the form
	 */
	java.awt.EventQueue.invokeLater(new Runnable()
	{

	    public void run()
	    {
		new FACECaseSummary().setVisible(true);
	    }
	});
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEdit;
    private javax.swing.JButton btnExitCase;
    private javax.swing.JScrollBar jScrollBar1;
    private javax.swing.JLabel lblCaseNumber;
    private javax.swing.JPanel pnlButtons;
    private javax.swing.JPanel pnlCaseNumber;
    private javax.swing.JPanel pnlDisplay;
    private javax.swing.JScrollPane scrRemainsList;
    private javax.swing.JTextArea txtRemainsList;
    // End of variables declaration//GEN-END:variables
}
