/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package prog24178.project;

import java.awt.event.*;
import java.io.File;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Scanner;
import javax.swing.JFrame;

/**
 *
 * @author mikkelharris
 */
public class OldFaceDetails extends JFrame implements ActionListener, WindowListener
{
    ArrayList boneArray = new ArrayList(50);
    /**
     * Creates new form OldFaceDetails
     */
    public OldFaceDetails(String setCase)
    {
	initComponents();
	btnSave.addActionListener(this);
	btnUpdate.addActionListener(this);
	btnBack.addActionListener(this);

	lblCaseNumber.setText(setCase);
	
    }
    
    public  OldFaceDetails()
    {
	
    }
    @Override
    public void actionPerformed(ActionEvent event)
    {
	Object source = event.getSource();
	
	if (source == btnBack)
	{
	    FACECaseSummary face1 = new FACECaseSummary(lblCaseNumber.getText());
	    face1.pack();
	    face1.setVisible(true);
	    this.setVisible(false);
	}
    }
    private void addToFound(Object bodyRegion)
    {
	
	
    }
    
    private void createArray(String casefile)
    {
	try
	{
	    Scanner fileIn = new Scanner(new File(casefile));
	    fileIn.useDelimiter(System.getProperty("line.separator"));
	    
	    while (fileIn.hasNext())
	    {
		String record = fileIn.next();
		
		Scanner recordIn = new Scanner(record);
		recordIn.useDelimiter("\\s*\\|\\s*");
		String caseNum = recordIn.next();
		String bodyRegion = recordIn.next();
		String boneName = recordIn.next();
		String condition = recordIn.next();
		String foundStatus = recordIn.next();
		
		boneArray.add(caseNum);
		
		

	    }
	    fileIn.close();
	    fileIn = null;
	}
	catch (IOException ex)
	{
	    
	}
	
    }	
    @Override
    public void windowDeactivated(WindowEvent event){}
    @Override
    public void windowActivated(WindowEvent event){}
    @Override
    public void windowDeiconified(WindowEvent event){}
    @Override
    public void windowIconified(WindowEvent event){}
    @Override
    public void windowClosed(WindowEvent event){}
    @Override
    public void windowClosing(WindowEvent event){}
    @Override
    public void windowOpened(WindowEvent event){}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlFound = new javax.swing.JPanel();
        ddlFoundRegion = new javax.swing.JComboBox();
        lblFoundRegion = new javax.swing.JLabel();
        scrFoundNotes = new javax.swing.JScrollPane();
        txtFoundNotes = new javax.swing.JTextArea();
        lblFoundNotes = new javax.swing.JLabel();
        chkFoundRecovered = new javax.swing.JCheckBox();
        scrFoundBones = new javax.swing.JScrollPane();
        lstFoundBones = new javax.swing.JList();
        btnBack = new javax.swing.JButton();
        btnSave = new javax.swing.JButton();
        pnlNotFound = new javax.swing.JPanel();
        ddlNotFoundRegion = new javax.swing.JComboBox();
        lblNotFoundRegion = new javax.swing.JLabel();
        scrNotFoundNotes = new javax.swing.JScrollPane();
        txtNotFoundNotes = new javax.swing.JTextArea();
        lblNotFoundNotes = new javax.swing.JLabel();
        chkNotFoundRecovered = new javax.swing.JCheckBox();
        scrNotFoundBones = new javax.swing.JScrollPane();
        lstNotFountBones = new javax.swing.JList();
        btnUpdate = new javax.swing.JButton();
        pnlCaseNumber = new javax.swing.JPanel();
        lblCaseNumber = new javax.swing.JLabel();
        lblCase = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setSize(new java.awt.Dimension(600, 450));

        pnlFound.setBorder(javax.swing.BorderFactory.createTitledBorder("Found"));

        ddlFoundRegion.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "All Regions", "Head", "Torso", "Spine", "Pelvis", "Right Arm", "Left Arm", "Right Hand", "Left Hand", "Right Leg", "Left Leg", "Right Foot", "Left Foot" }));

        lblFoundRegion.setText("Body Region:");

        scrFoundNotes.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        txtFoundNotes.setColumns(20);
        txtFoundNotes.setRows(5);
        scrFoundNotes.setViewportView(txtFoundNotes);

        lblFoundNotes.setText("Notes on Bone:");

        chkFoundRecovered.setText("Bone Recovered");

        scrFoundBones.setViewportView(lstFoundBones);

        btnBack.setText("Back");
        btnBack.setSize(new java.awt.Dimension(100, 29));

        btnSave.setText("Save Record");

        org.jdesktop.layout.GroupLayout pnlFoundLayout = new org.jdesktop.layout.GroupLayout(pnlFound);
        pnlFound.setLayout(pnlFoundLayout);
        pnlFoundLayout.setHorizontalGroup(
            pnlFoundLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(pnlFoundLayout.createSequentialGroup()
                .add(ddlFoundRegion, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(0, 0, Short.MAX_VALUE))
            .add(pnlFoundLayout.createSequentialGroup()
                .addContainerGap()
                .add(pnlFoundLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                    .add(org.jdesktop.layout.GroupLayout.LEADING, pnlFoundLayout.createSequentialGroup()
                        .add(scrFoundBones, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 119, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .add(12, 12, 12)
                        .add(pnlFoundLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(pnlFoundLayout.createSequentialGroup()
                                .add(lblFoundNotes)
                                .addContainerGap())
                            .add(pnlFoundLayout.createSequentialGroup()
                                .add(scrFoundNotes, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                                .add(12, 12, 12))))
                    .add(pnlFoundLayout.createSequentialGroup()
                        .add(pnlFoundLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(btnSave)
                            .add(lblFoundRegion))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .add(pnlFoundLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(org.jdesktop.layout.GroupLayout.TRAILING, pnlFoundLayout.createSequentialGroup()
                                .add(chkFoundRecovered)
                                .add(25, 25, 25))
                            .add(org.jdesktop.layout.GroupLayout.TRAILING, pnlFoundLayout.createSequentialGroup()
                                .add(btnBack)
                                .add(22, 22, 22))))))
        );

        pnlFoundLayout.linkSize(new java.awt.Component[] {btnBack, btnSave}, org.jdesktop.layout.GroupLayout.HORIZONTAL);

        pnlFoundLayout.setVerticalGroup(
            pnlFoundLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(pnlFoundLayout.createSequentialGroup()
                .add(pnlFoundLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(lblFoundRegion)
                    .add(chkFoundRecovered))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(pnlFoundLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(ddlFoundRegion, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(lblFoundNotes))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(pnlFoundLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                    .add(scrFoundBones)
                    .add(scrFoundNotes))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 8, Short.MAX_VALUE)
                .add(pnlFoundLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(btnBack)
                    .add(btnSave)))
        );

        pnlNotFound.setBorder(javax.swing.BorderFactory.createTitledBorder("Not Found"));

        ddlNotFoundRegion.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "All Regions", "Head", "Torso", "Spine", "Pelvis", "Right Arm", "Left Arm", "Right Hand", "Left Hand", "Right Leg", "Left Leg", "Right Foot", "Left Foot" }));

        lblNotFoundRegion.setText("Body Region:");

        scrNotFoundNotes.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        txtNotFoundNotes.setColumns(20);
        txtNotFoundNotes.setRows(5);
        scrNotFoundNotes.setViewportView(txtNotFoundNotes);

        lblNotFoundNotes.setText("Notes on Bone:");

        chkNotFoundRecovered.setText("Bone Recovered");

        scrNotFoundBones.setViewportView(lstNotFountBones);

        btnUpdate.setText("Update");

        org.jdesktop.layout.GroupLayout pnlNotFoundLayout = new org.jdesktop.layout.GroupLayout(pnlNotFound);
        pnlNotFound.setLayout(pnlNotFoundLayout);
        pnlNotFoundLayout.setHorizontalGroup(
            pnlNotFoundLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(pnlNotFoundLayout.createSequentialGroup()
                .addContainerGap()
                .add(pnlNotFoundLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                    .add(pnlNotFoundLayout.createSequentialGroup()
                        .add(lblNotFoundRegion)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 36, Short.MAX_VALUE)
                        .add(chkNotFoundRecovered)
                        .add(26, 26, 26))
                    .add(org.jdesktop.layout.GroupLayout.LEADING, pnlNotFoundLayout.createSequentialGroup()
                        .add(scrNotFoundBones, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 119, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                        .add(pnlNotFoundLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(pnlNotFoundLayout.createSequentialGroup()
                                .add(lblNotFoundNotes)
                                .add(0, 0, Short.MAX_VALUE))
                            .add(scrNotFoundNotes, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                        .addContainerGap())))
            .add(pnlNotFoundLayout.createSequentialGroup()
                .add(pnlNotFoundLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(ddlNotFoundRegion, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(pnlNotFoundLayout.createSequentialGroup()
                        .add(77, 77, 77)
                        .add(btnUpdate, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 117, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        pnlNotFoundLayout.setVerticalGroup(
            pnlNotFoundLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(pnlNotFoundLayout.createSequentialGroup()
                .add(pnlNotFoundLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(lblNotFoundRegion)
                    .add(chkNotFoundRecovered))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(pnlNotFoundLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(ddlNotFoundRegion, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(lblNotFoundNotes))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(pnlNotFoundLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                    .add(scrNotFoundNotes)
                    .add(scrNotFoundBones, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 134, Short.MAX_VALUE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .add(btnUpdate))
        );

        lblCaseNumber.setText(" ");
        lblCaseNumber.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        lblCase.setText("Case Number:");

        org.jdesktop.layout.GroupLayout pnlCaseNumberLayout = new org.jdesktop.layout.GroupLayout(pnlCaseNumber);
        pnlCaseNumber.setLayout(pnlCaseNumberLayout);
        pnlCaseNumberLayout.setHorizontalGroup(
            pnlCaseNumberLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, pnlCaseNumberLayout.createSequentialGroup()
                .addContainerGap()
                .add(lblCase)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(lblCaseNumber, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 83, Short.MAX_VALUE)
                .add(412, 412, 412))
        );
        pnlCaseNumberLayout.setVerticalGroup(
            pnlCaseNumberLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(pnlCaseNumberLayout.createSequentialGroup()
                .addContainerGap()
                .add(pnlCaseNumberLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(lblCaseNumber)
                    .add(lblCase))
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(layout.createSequentialGroup()
                        .add(pnlNotFound, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(pnlFound, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                    .add(pnlCaseNumber, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(6, 6, 6))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                .add(pnlCaseNumber, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(pnlFound, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(pnlNotFound, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
	/*
	 * Set the Nimbus look and feel
	 */
	//<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
	 * If Nimbus (introduced in Java SE 6) is not available, stay with the
	 * default look and feel. For details see
	 * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
	 */
	try
	{
	    for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
	    {
		if ("Nimbus".equals(info.getName()))
		{
		    javax.swing.UIManager.setLookAndFeel(info.getClassName());
		    break;
		}
	    }
	} catch (ClassNotFoundException ex)
	{
	    java.util.logging.Logger.getLogger(OldFaceDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
	} catch (InstantiationException ex)
	{
	    java.util.logging.Logger.getLogger(OldFaceDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
	} catch (IllegalAccessException ex)
	{
	    java.util.logging.Logger.getLogger(OldFaceDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
	} catch (javax.swing.UnsupportedLookAndFeelException ex)
	{
	    java.util.logging.Logger.getLogger(OldFaceDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
	}
	//</editor-fold>

	/*
	 * Create and display the form
	 */
	java.awt.EventQueue.invokeLater(new Runnable()
	{

	    public void run()
	    {
		new OldFaceDetails().setVisible(true);
	    }
	});
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnSave;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JCheckBox chkFoundRecovered;
    private javax.swing.JCheckBox chkNotFoundRecovered;
    private javax.swing.JComboBox ddlFoundRegion;
    private javax.swing.JComboBox ddlNotFoundRegion;
    private javax.swing.JLabel lblCase;
    private javax.swing.JLabel lblCaseNumber;
    private javax.swing.JLabel lblFoundNotes;
    private javax.swing.JLabel lblFoundRegion;
    private javax.swing.JLabel lblNotFoundNotes;
    private javax.swing.JLabel lblNotFoundRegion;
    private javax.swing.JList lstFoundBones;
    private javax.swing.JList lstNotFountBones;
    private javax.swing.JPanel pnlCaseNumber;
    private javax.swing.JPanel pnlFound;
    private javax.swing.JPanel pnlNotFound;
    private javax.swing.JScrollPane scrFoundBones;
    private javax.swing.JScrollPane scrFoundNotes;
    private javax.swing.JScrollPane scrNotFoundBones;
    private javax.swing.JScrollPane scrNotFoundNotes;
    private javax.swing.JTextArea txtFoundNotes;
    private javax.swing.JTextArea txtNotFoundNotes;
    // End of variables declaration//GEN-END:variables
}
